import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Heart,
  Download,
  Share2,
  Save,
  MoreVertical,
  Copy,
  Mail,
  Check,
  Loader2,
  FileText,
} from "lucide-react";
import { TripDetails, Recommendations } from "@/types/trip";
import { toast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";

interface TripActionsProps {
  tripDetails: TripDetails;
  recommendations: Recommendations;
  onSaveTrip?: () => Promise<void>;
  isSaving?: boolean;
}

const TripActions = ({
  tripDetails,
  recommendations,
  onSaveTrip,
  isSaving,
}: TripActionsProps) => {
  const [isFavorite, setIsFavorite] = useState(false);
  const [isShareOpen, setIsShareOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleFavorite = () => {
    setIsFavorite(!isFavorite);
    toast({
      title: isFavorite ? "Removed from favorites" : "Added to favorites",
      description: isFavorite
        ? "Trip removed from your favorites"
        : "Trip saved to your favorites for quick access",
    });
  };

  const generateTripText = () => {
    const places = recommendations.touristPlaces
      .map((p) => `- ${p.name}: ${p.description}`)
      .join("\n");
    const hotels = recommendations.hotels
      .map((h) => `- ${h.name} (${h.pricePerNight}/night, ${h.rating}★)`)
      .join("\n");
    const vehicles = recommendations.vehicles
      .map((v) => `- ${v.type}: ${v.estimatedCost}`)
      .join("\n");

    return `🌍 Travello Trip Plan
━━━━━━━━━━━━━━━━━━━━━━━━

📍 ${tripDetails.boardingPoint} → ${tripDetails.destinationPoint}
📅 Duration: ${tripDetails.duration} days
💰 Budget: $${tripDetails.budget}

📸 Tourist Places:
${places}

🏨 Recommended Hotels:
${hotels}

🚗 Transportation:
${vehicles}

💡 Summary:
${recommendations.summary}

---
Generated by Travello - AI Trip Planning`;
  };

  const handleDownload = () => {
    const content = generateTripText();
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `travello-${tripDetails.destinationPoint.toLowerCase().replace(/[^a-z0-9]/g, "-")}-trip.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast({
      title: "Trip plan downloaded!",
      description: "Your trip plan has been saved as a text file",
    });
  };

  const handleCopyLink = async () => {
    const content = generateTripText();
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    toast({
      title: "Copied to clipboard!",
      description: "Trip details copied to your clipboard",
    });
  };

  const handleEmailShare = () => {
    const subject = `Trip Plan: ${tripDetails.boardingPoint} to ${tripDetails.destinationPoint}`;
    const body = encodeURIComponent(generateTripText());
    window.open(`mailto:?subject=${encodeURIComponent(subject)}&body=${body}`);
  };

  return (
    <div className="flex items-center gap-2">
      {/* Favorite button */}
      <Button
        variant="outline"
        size="icon"
        onClick={handleFavorite}
        className={cn(
          "transition-all",
          isFavorite && "bg-red-50 border-red-200 hover:bg-red-100"
        )}
      >
        <Heart
          className={cn(
            "w-4 h-4 transition-all",
            isFavorite ? "fill-red-500 text-red-500" : "text-muted-foreground"
          )}
        />
      </Button>

      {/* Save to history */}
      {onSaveTrip && (
        <Button
          variant="outline"
          size="sm"
          onClick={onSaveTrip}
          disabled={isSaving}
          className="gap-2"
        >
          {isSaving ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <Save className="w-4 h-4" />
          )}
          Save Trip
        </Button>
      )}

      {/* Download button */}
      <Button variant="outline" size="icon" onClick={handleDownload}>
        <Download className="w-4 h-4" />
      </Button>

      {/* Share button */}
      <Button
        variant="outline"
        size="icon"
        onClick={() => setIsShareOpen(true)}
      >
        <Share2 className="w-4 h-4" />
      </Button>

      {/* More options */}
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="outline" size="icon">
            <MoreVertical className="w-4 h-4" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-48">
          <DropdownMenuItem onClick={handleDownload}>
            <FileText className="w-4 h-4 mr-2" />
            Download as TXT
          </DropdownMenuItem>
          <DropdownMenuItem onClick={handleCopyLink}>
            <Copy className="w-4 h-4 mr-2" />
            Copy to clipboard
          </DropdownMenuItem>
          <DropdownMenuSeparator />
          <DropdownMenuItem onClick={handleEmailShare}>
            <Mail className="w-4 h-4 mr-2" />
            Share via Email
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>

      {/* Share Dialog */}
      <Dialog open={isShareOpen} onOpenChange={setIsShareOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Share Trip Plan</DialogTitle>
            <DialogDescription>
              Share your trip to {tripDetails.destinationPoint} with friends and family
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="flex items-center gap-2">
              <Button
                variant="outline"
                className="flex-1 gap-2"
                onClick={handleCopyLink}
              >
                {copied ? (
                  <>
                    <Check className="w-4 h-4 text-green-500" />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4" />
                    Copy Trip Details
                  </>
                )}
              </Button>
              <Button
                variant="outline"
                className="flex-1 gap-2"
                onClick={handleEmailShare}
              >
                <Mail className="w-4 h-4" />
                Email
              </Button>
            </div>
          </div>
          <DialogFooter>
            <Button variant="ghost" onClick={() => setIsShareOpen(false)}>
              Close
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default TripActions;
